name: New Agent request
description: Submit a proposal/request for a new agent
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this agent request!
  - type: checkboxes
    attributes:
      label: Confirm this is a new agent request
      options:
        - label: I've checked the current issues, and there's no record of this agent request
          required: false
  - type: textarea
    attributes:
      label: Describe the agent
      description: >
        Provide a clear, concise overview of what this agent needs to do and why it is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context about the agent request here.
    validations:
      required: false
