name: Feature
description: Submit a proposal/request for a new feature
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Confirm this is a new feature request
      options:
        - label: I've checked the current issues, and there's no record of this feature request
          required: false
  - type: textarea
    attributes:
      label: Describe the feature
      description: >
        A clear and concise description of what the feature is and why it's needed. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context about the feature request here.
    validations:
      required: false
