name: New Tool request
description: Submit a proposal/request for a new Tool
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this tool request!
  - type: checkboxes
    attributes:
      label: Confirm this is a new tool request
      options:
        - label: I've checked the current issues, and there's no record of this tool request
          required: false
  - type: textarea
    attributes:
      label: Describe the tool
      description: >
        A clear and concise description of what the tool is and why it's needed. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >
        A clear and concise description of any alternative solutions you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context about the tool request here.
    validations:
      required: false
